const UNKNOWN = '10-0'

const AUTHENTICATION_ERROR = '11-1'
const AUTHORIZATION_ERROR = '11-2'
const REGISTRATION_NOT_COMPLETED = '11-3'

const REQUEST_VALIDATION_ERROR = '12-1'
const CAPTHA_VALIDATION_ERROR = '12-2'
const EMAIL_VALIDATION_ERROR = '12-3'
const EMAIL_REQUIRED = '12-4'
const ACCOUNT_EXISTS = '12-5'
const ACCOUNT_NOT_EXISTS = '12-6'
const ACTIVATION_DATA_NOT_EXISTS = '12-7'
const PASSWORD_INPUTS_DO_NOT_MATCH = '12-8'
const PASSWORD_INPUTS_MATCH = '12-9'
const PASSWORD_REQUIRED = '12-10'
const PASSWORD_LENGTH = '12-11'
const PASSWORD_VALIDATION_ERROR = '12-12'
const BAD_CREDENTIALS = '12-13'
const INVALID_RESET_PASSWORD_TOKEN_ERROR = '12-14'

module.exports = {
  UNKNOWN,

  AUTHENTICATION_ERROR,
  AUTHORIZATION_ERROR,
  REGISTRATION_NOT_COMPLETED,

  REQUEST_VALIDATION_ERROR,
  CAPTHA_VALIDATION_ERROR,
  EMAIL_VALIDATION_ERROR,
  EMAIL_REQUIRED,
  ACCOUNT_EXISTS,
  ACCOUNT_NOT_EXISTS,
  ACTIVATION_DATA_NOT_EXISTS,
  PASSWORD_INPUTS_DO_NOT_MATCH,
  PASSWORD_INPUTS_MATCH,
  PASSWORD_REQUIRED,
  PASSWORD_LENGTH,
  PASSWORD_VALIDATION_ERROR,
  BAD_CREDENTIALS,
  INVALID_RESET_PASSWORD_TOKEN_ERROR,
}
